[package]
name = "rust_dijkstras"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "4.1.1"
priority-queue = "1.3.2"
rand = "0.8.5"
